[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_yaml.workspace = true
toml.workspace = true
regex.workspace = true