[package]
name = "asciidoctor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-std.workspace = true
serde.workspace = true
serde_json.workspace = true
deno_core.workspace = true
once_cell.workspace = true

[dev-dependencies]
futures-await-test.workspace = true