name: Release

on:
  push:
    #    branches: [ "master" ]
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
#  pull_request:
#    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  APP_NAME: beerduck

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    strategy:
      matrix:
        entry:
          -
            os: macos-latest
            target: x86_64-apple-darwin
            suffix: ""
          -
            os: macos-latest
            target: aarch64-apple-darwin
            suffix: ""
          -
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ""
#          -
#            os: ubuntu-latest
#            target: x86_64-unknown-linux-musl
#            suffix: ""
          -
            os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: ".exe"
#          -
#            os: windows-latest
#            target: i686-pc-windows-msvc
#            suffix: ".exe"

    runs-on: ${{ matrix.entry.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Add target
        run: rustup update && rustup target add ${{ matrix.entry.target }}
      - name: Build binary
        run: cargo build --release --target=${{ matrix.entry.target }}
      - name: Compress zip
        uses: vimtor/action-zip@v1
        with:
          files: target/${{ matrix.entry.target }}/release/${{env.APP_NAME}}${{ matrix.entry.suffix }}
          dest: target/${{ matrix.entry.target }}/release/${{env.APP_NAME}}-${{ matrix.entry.target }}.zip
      - name: Upload ${{env.APP_NAME}}-${{ matrix.entry.target }}.zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.entry.target }}/release/${{env.APP_NAME}}-${{ matrix.entry.target }}.zip
          asset_name: ${{env.APP_NAME}}-${{ matrix.entry.target }}.zip
          tag: ${{ github.ref }}
